module.exports = {
  tokenMapping: {
    USDT: 'USD',
    USDC: 'UDC',
    MANA: 'MNA',
  },
  USDTMapping: {
    // dvf to bfx
    tETHUSD: 'tETHUST',
    tBTCUSD: 'tBTCUST',
    'tLINK:USD': 'tLINK:UST',
    'tCOMP:USD': 'tCOMP:UST',
    tUNIUSD: 'tUNIUST',
    tYFIUSD: 'tYFIUST',
    'tSUSHI:USD': 'tSUSHI:UST',
    tUDCUSD: 'tUDCUST',
    tETHUDC: 'tETHUST',
    tBTCUDC: 'tBTCUST',
    't1INCH:USD': 't1INCH:UST',
    'tMATIC:USD': 'tMATIC:UST',
    'tAAVE:USD': 'tAAVE:UST',
    'tSPELL:USD': 'tSPELL:USD',
    'tMANA:USD': 'tMNAUSD',
    tCRVUSD: 'tCRVUST',
    // bfx to dvf
    'ETH:UST': 'ETH:USDT',
    'BTC:UST': 'BTC:USDT',
    'LINK:UST': 'LINK:USDT',
    'COMP:UST': 'COMP:USDT',
    'UNI:UST': 'UNI:USDT',
    'YFI:UST': 'YFI:USDT',
    'SUSHI:UST': 'SUSHI:USDT',
    'UDC:UST': 'USDC:USDT',
    '1INCH:UST': '1INCH:USDT',
    'MATIC:UST': 'MATIC:USDT',
    'AAVE:UST': 'AAVE:USDT',
    'SPELL:USD': 'SPELL:USDT',
    'MNA:USDT': 'MANA:USDT',
    'CRV:UST': 'CRV:USDT',
  },
}
